[pytest]
testpaths =
    workflows/tests
    contracts/engine/tests
    contracts/traffic/tests
    tests/traffic
    tests/weather
norecursedirs =
    .git
    .pytest_cache
    .tox
    .venv
    venv
    __pycache__
    dbt_packages
    target
    logs
