-- silver_license_detail_health — 보건 대분류 '분야별(개별) 영역' 큰 정보 단위 (#80)
-- 공통/주소/좌표는 silver_license_current 에 있고, 여기서는 보건 업종군 고유 컬럼만 record_json 에서 추출한다.
-- 해당 군에 없는 필드는 자동 null(schema-on-read) — 완전 정규화(필드별 소테이블) 하지 않는다.
-- grain: (dataset, opnsfteamcode, mgtno). 필드 사전/근거: docs/dataset-columns.md §3.

{{ config(materialized='table') }}

with base as (
    select c.*, t.category, t.sub_category
    from {{ ref('silver_license_current') }} c
    join {{ ref('commerce_dataset_taxonomy') }} t on t.short = c.dataset
    where t.major = 'health'
)

select
    dataset,
    opnsfteamcode,
    mgtno,
    category,          -- 중분류(식품/의료/…)
    sub_category,      -- 명칭분류
    bplcnm,
    trdstatenm,
    -- ── 식품(food) 개별 48 ──
    {{ lf('HOMEPAGE') }} as homepage,
    {{ lf('JTUPSOASGNNO') }} as jtupsoasgnno,
    {{ lf('MULTUSNUPSOYN') }} as multusnupsoyn,
    {{ lf('FCTYPDTJOBEPCNT') }} as fctypdtjobepcnt,
    {{ lf('JTUPSOMAINEDF') }} as jtupsomainedf,
    {{ lf('FCTYSILJOBEPCNT') }} as fctysiljobepcnt,
    {{ lf('HOFFEPCNT') }} as hoffepcnt,
    {{ lf('MONAM') }} as monam,
    {{ lf('LVSENM') }} as lvsenm,
    {{ lf('WMEIPCNT') }} as wmeipcnt,
    {{ lf('SNTUPTAENM') }} as sntuptaenm,
    {{ lf('WTRSPLYFACILSENM') }} as wtrsplyfacilsenm,
    {{ lf('FACILTOTSCP') }} as faciltotscp,
    {{ lf('BDNGOWNSENM') }} as bdngownsenm,
    {{ lf('MANEIPCNT') }} as maneipcnt,
    {{ lf('FCTYOWKEPCNT') }} as fctyowkepcnt,
    {{ lf('ISREAM') }} as isream,
    {{ lf('TRDPJUBNSENM') }} as trdpjubnsenm,
    {{ lf('UPTAENM') }} as uptaenm,
    {{ lf('CAPT') }} as capt,
    {{ lf('CHAIRCNT') }} as chaircnt,
    {{ lf('SHPCNT') }} as shpcnt,
    {{ lf('STROOMCNT') }} as stroomcnt,
    {{ lf('MEETSAMTIMESYGSTF') }} as meetsamtimesygstf,
    {{ lf('MNFACTREARTCLCN') }} as mnfactreartclcn,
    {{ lf('SHPTOTTONS') }} as shptottons,
    {{ lf('CULPHYEDCOBNM') }} as culphyedcobnm,
    {{ lf('INSURENDDT') }} as insurenddt,
    {{ lf('APVCANCELYMD') }} as apvcancelymd,
    {{ lf('INSURSTDT') }} as insurstdt,
    {{ lf('ENGSTNTRNMNM') }} as engstntrnmnm,
    {{ lf('SVNSR') }} as svnsr,
    {{ lf('INSURORGNM') }} as insurorgnm,
    {{ lf('REGNSENM') }} as regnsenm,
    {{ lf('FACILAR') }} as facilar,
    {{ lf('CLGENDDT') }} as clgenddt,
    {{ lf('CULWRKRSENM') }} as culwrkrsenm,
    {{ lf('UNDERNUMLAY') }} as undernumlay,
    {{ lf('BDNGSRVNM') }} as bdngsrvnm,
    {{ lf('FACILSCP') }} as facilscp,
    {{ lf('ENGSTNTRNMADDR') }} as engstntrnmaddr,
    {{ lf('STAGEAR') }} as stagear,
    {{ lf('TOTNUMLAY') }} as totnumlay,
    {{ lf('CLGSTDT') }} as clgstdt,
    {{ lf('NEARENVNM') }} as nearenvnm,
    {{ lf('SHPINFO') }} as shpinfo,
    {{ lf('JISGNUMLAY') }} as jisgnumlay,
    {{ lf('CNSTYAREA') }} as cnstyarea,
    -- ── 의료(health_medical) 개별 31 ──
    {{ lf('SICBNUM') }} as sicbnum,
    {{ lf('TOTAR') }} as totar,
    {{ lf('MEDEXTRITEMSCNNM') }} as medextritemscnnm,
    {{ lf('METRPNUM') }} as metrpnum,
    {{ lf('MEDEXTRITEMSCN') }} as medextritemscn,
    {{ lf('METRORGASSRNM') }} as metrorgassrnm,
    {{ lf('HSTRMNUM') }} as hstrmnum,
    {{ lf('NURSECNT') }} as nursecnt,
    {{ lf('COPNUM') }} as copnum,
    {{ lf('NURSAIDCNT') }} as nursaidcnt,
    {{ lf('MMKNURMAR') }} as mmknurmar,
    {{ lf('POMFACILAR') }} as pomfacilar,
    {{ lf('WARMAR') }} as warmar,
    {{ lf('BABYRGLSTNUM') }} as babyrglstnum,
    {{ lf('NUTRCNT') }} as nutrcnt,
    {{ lf('JORIWONTOILAR') }} as joriwontoilar,
    {{ lf('PGRMAR') }} as pgrmar,
    {{ lf('BBRMAR') }} as bbrmar,
    {{ lf('OFEAR') }} as ofear,
    {{ lf('PWNMRGLSTNUM') }} as pwnmrglstnum,
    {{ lf('BDNGLAYERCNT') }} as bdnglayercnt,
    {{ lf('BTRMAR') }} as btrmar,
    {{ lf('BTPNUM') }} as btpnum,
    {{ lf('STORETRDAR') }} as storetrdar,
    {{ lf('BATRAR') }} as batrar,
    {{ lf('QUTNOWNERNUM') }} as qutnownernum,
    {{ lf('EPCNT') }} as epcnt,
    {{ lf('ETCEPCNT') }} as etcepcnt,
    {{ lf('ASTNEPNUM') }} as astnepnum,
    {{ lf('METRBOSASSRNM') }} as metrbosassrnm,
    {{ lf('FACILMNGNUM') }} as facilmngnum,
    -- ── 위생·미용(hygiene_beauty) 개별 23 ──
    {{ lf('CNDPERMENDYMD') }} as cndpermendymd,
    {{ lf('CNDPERMNTWHY') }} as cndpermntwhy,
    {{ lf('USEUNDERSTFLR') }} as useunderstflr,
    {{ lf('USEUNDERENDFLR') }} as useunderendflr,
    {{ lf('BDNGJISGFLRCNT') }} as bdngjisgflrcnt,
    {{ lf('CNDPERMSTYMD') }} as cndpermstymd,
    {{ lf('USEJISGENDFLR') }} as usejisgendflr,
    {{ lf('USEJISGSTFLR') }} as usejisgstflr,
    {{ lf('BDNGUNDERFLRCNT') }} as bdngunderflrcnt,
    {{ lf('ABEDCNT') }} as abedcnt,
    {{ lf('RCVDRYNCNT') }} as rcvdryncnt,
    {{ lf('WASHMCCNT') }} as washmccnt,
    {{ lf('DISFETVEHGARAR') }} as disfetvehgarar,
    {{ lf('DYNPWSPRAYNUM') }} as dynpwspraynum,
    {{ lf('MICROSPKLNUM') }} as microspklnum,
    {{ lf('PROTGLSNUM') }} as protglsnum,
    {{ lf('HDOPTDSPRAYNUM') }} as hdoptdspraynum,
    {{ lf('PROTUSECLOTNUM') }} as protuseclotnum,
    {{ lf('VACUCLERNUM') }} as vacuclernum,
    {{ lf('GMKNUM') }} as gmknum,
    {{ lf('HNDUSESTLZNUM') }} as hndusestlznum,
    {{ lf('YOKSILCNT') }} as yoksilcnt,
    {{ lf('BALHANSILYN') }} as balhansilyn,
    -- ── 안경·치과(optical_dental) 개별 24 ──
    {{ lf('VITRNUM') }} as vitrnum,
    {{ lf('EFURNUM') }} as efurnum,
    {{ lf('ACETNUM') }} as acetnum,
    {{ lf('CTPLCTMCENUM') }} as ctplctmcenum,
    {{ lf('SPWVCLERNUM') }} as spwvclernum,
    {{ lf('CRFTUSEMOTNUM') }} as crftusemotnum,
    {{ lf('CRFTUSECOMPRECNT') }} as crftusecomprecnt,
    {{ lf('BURYCNT') }} as burycnt,
    {{ lf('DENTIUSEPRESSNUM') }} as dentiusepressnum,
    {{ lf('CRFTUSELESSNUM') }} as crftuselessnum,
    {{ lf('PCANNUM') }} as pcannum,
    {{ lf('SBMCNT') }} as sbmcnt,
    {{ lf('TRMNUM') }} as trmnum,
    {{ lf('SUVYNUM') }} as suvynum,
    {{ lf('PINDEXCNT') }} as pindexcnt,
    {{ lf('HEATNUM') }} as heatnum,
    {{ lf('MSMCHAIRNUM') }} as msmchairnum,
    {{ lf('PUPILDISTMEASNUM') }} as pupildistmeasnum,
    {{ lf('GLSWASHERNUM') }} as glswashernum,
    {{ lf('DEFPTRFRTGGNUM') }} as defptrfrtggnum,
    {{ lf('LENSCUTNUM') }} as lenscutnum,
    {{ lf('PPTNUSEGRNDNUM') }} as pptnusegrndnum,
    {{ lf('EYEPYONUM') }} as eyepyonum,
    {{ lf('SAMPLENSNUM') }} as samplensnum,
    -- ── 숙박(lodging) 개별 4 ──
    {{ lf('HANSHILCNT') }} as hanshilcnt,
    {{ lf('SNTTN_BZSTAT_NM') }} as snttn_bzstat_nm,
    {{ lf('LOTNO_ADDR') }} as lotno_addr,
    {{ lf('YANGSILCNT') }} as yangsilcnt,
    -- ── 축산(livestock) 개별 5 ──
    {{ lf('LINDJOBGBNNM') }} as lindjobgbnnm,
    {{ lf('RGTMBDSNO') }} as rgtmbdsno,
    {{ lf('ROPNYMD') }} as ropnymd,
    {{ lf('LINDSEQNO') }} as lindseqno,
    {{ lf('LINDPRCBGBNNM') }} as lindprcbgbnnm,
    -- ── 동물(animal) 개별 1 ──
    {{ lf('CFRMGBNCTN') }} as cfrmgbnctn,
    -- ── 약국(pharmacy) 개별 2 ──
    {{ lf('ASGNYMD') }} as asgnymd,
    {{ lf('PHARMTRDAR') }} as pharmtrdar,
    -- 원본 보존(미추출 필드 소급 + gold table화)
    record_json,
    updatedt_ts,
    lastmodts_ts,
    observed_date,
    collected_at,
    load_date
from base
